name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Display the pathh
        run: ls -a
        shell: bash

      - name: Create environment file
        run: |
          echo $DEV_ENV_FILE > .env
        shell: bash
        env:
          DEV_ENV_FILE: ${{secrets.DEV_ENV_FILE}}

      - name: Display the path
        run: ls -a
        shell: bash

      - name: Cat env
        run: |
          cat .env
        shell: bash

      - name: Display the path
        run: ls -a
        shell: bash

      - name: Start all the environment
        run: docker-compose up -d

      - name: Wait for the environment to get up
        run: |
          while ! make ping-mysql &>/dev/null; do
              echo "Waiting for database connection..."
              sleep 2
          done

      - name: Run the tests
        run: make docker-test

